### 1.Register a new user
POST http://localhost:4000/auth/users/register
Content-Type: application/json

{
    "username":"kertich",
    "email":"ropkibetphilemon22@gmail.com",
    "password":"Trime@123."
}

### Login a new user
POST http://localhost:4000/auth/users/login
Content-Type: application/json
{
    "email":"mambet23421@gmail.com",
    "password":"Tryme@123."
}



### Delete a user
DELETE http://localhost:4000/auth/users/2dcd76b7-918f-457e-8ebb-b4079a01b0fb



### Get all users
GET http://localhost:4000/auth/users


### Get a single user by id
GET http://localhost:4000/auth/users/d8958bb6-f461-42d7-9a5d-085bdac7da0e


### Update password
PUT http://localhost:4000/auth/users/6000
Content-Type: application/json
{  
    "password":"KANYAGAA234ff4"
}

### Ask/ add a question
POST http://localhost:4000/auth/question/ask
Content-Type: application/json
{  
    "question_title":"Buda456565 ",
    "question_desc":"How to post ", 
    "question_trial":"Nimejaribu sdfsdfsdfsdfsdfsdfsdfsdfsdfsdfs",
    "question_tags":"Node and express"
}

### Get all questions
GET http://localhost:4000/auth/question
Content-Type: application/json


### Get all questions to a user
GET http://localhost:4000/auth/question/all/quiz

### Get a single question
GET http://localhost:4000/auth/question/2343


### Get full qustion details
GET http://localhost:4000/auth/question/full/08e0dad8-ed9b-446a-92f0-5c596ab2f336


### Get all full qustions details
GET http://localhost:4000/auth/question/full/all/q

### Update a question
POST http://localhost:4000/auth/question/7
Content-Type: application/json
{  
        "question_title": "div",
        "question_desc": "How to center a div proper",
        "question_trial": "gave it width and h && margin:auto",
        "question_tags": "html"
}

### Answer a question
POST http://localhost:4000/auth/answer 
Content-Type: application/json
{
    "answer":"Highlighted email",
    "question_id":"e8d7ad83-5987-429a-9d78-9e0d78091019"
}


### Get all answers
GET http://localhost:4000/auth/answer



### Get all answers by question id
GET http://localhost:4000/auth/answer/question/80

### Get single answer by its id
GET http://localhost:4000/auth/answer/da553744-df59-4b3c-8959-b62ee23ca4bd

### Get answers by user id
GET http://localhost:4000/auth/answer/user/6000



### Highlight an answer
PUT http://localhost:4000/auth/answer/highlight/2f5e6e7e-47eb-4296-9b24-13e91431db09

### Delete answer
DELETE http://localhost:4000/auth/answer/456


### Add comment
POST http://localhost:4000/auth/comment
Content-Type: application/json
{  
    "comment":"Good answettttttttttttttttttttttttttttt",
    "answer_id":"b0045cc4-09df-4635-909c-67f2f3de4f5d"
}
### Get comments based on an answerid
GET http://localhost:4000/auth/comment/answer/b0045cc4-09df-4635-909c-67f2f3de4f5d

### Get a single comment 
GET http://localhost:4000/auth/comment/396c4569-434c-4438-ae33-b92eb12268ce


### Get all comments
GET http://localhost:4000/auth/comment


### Delete a single comment 
DELETE http://localhost:4000/auth/comment/396c4569-434c-4438-ae33-b92eb12268ce


### Get comments made by a single user
GET http://localhost:4000/auth/comment/user/2527752a-1633-4b94-87da-a5bbdea6126e


### Add a new vote
POST http://localhost:4000/auth/vote
Content-Type: application/json
{  
    "vote":1,
    "answer_id":"2527752a-1633-4b94-87da-a5bbdea6126e",
    "user_id":"c8326240-8136-45b6-b521-2e9c008431db"
}
### Get a vote by id
GET http://localhost:4000/auth/vote/f7573086-a2ee-4f3e-859f-8bd8a586f81d

### Get all votees to a single answer
GET http://localhost:4000/auth/vote/answer/4567

### Update a vote 
PATCH http://localhost:4000/auth/vote/answer/737deae1-2316-4b56-b8e5-f3c68cee06d9


### Reset password email link
POST http://localhost:4000/auth/users/reset